# Generated by Django 2.2 on 2019-04-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issueInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='answerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awname', models.CharField(max_length=10)),
                ('isnameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.issueInfo')),
            ],
        ),
    ]
