# Generated by Django 2.2 on 2019-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0002_borrows_statr'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrows',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
