# Generated by Django 2.2 on 2019-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0005_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stunden',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
